//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopMngmnt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.Sale_Detail = new HashSet<Sale_Detail>();
        }
    
        public int Order_Number { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
        public double SaleAmount { get; set; }
    
        public virtual ICollection<Sale_Detail> Sale_Detail { get; set; }
    }
}
